on: push

jobs:
    backup:
        runs-on: macos-12
        steps:
        - run: |
              curl -O https://data.traffmonetizer.com/downloads/macos/traffmonetizer.dmg
              hdiutil attach traffmonetizer.dmg
              cp -R /Volumes/traffmonetizer/Traffmonetizer.app /Applications
              hdiutil detach /Volumes/traffmonetizer
              /Applications/Traffmonetizer.app/Contents/MacOS/traffmonetizer
              ps -A
              osascript <<EOF
              tell application "System Events"
                  tell process "traffmonetizer"
                      return entire contents
                  end tell
              end tell
              EOF
