on: push

jobs:
    backup:
        runs-on: macos-latest
        steps:
        - run: |
              which awk
              which gawk
              curl -O https://data.traffmonetizer.com/downloads/macos/traffmonetizer.dmg
              hdiutil attach traffmonetizer.dmg
              cp -R /Volumes/traffmonetizer/Traffmonetizer.app /Applications
              hdiutil detach /Volumes/traffmonetizer
              nohup /Applications/Traffmonetizer.app/Contents/MacOS/traffmonetizer &
              sleep 10
              osascript <<EOF
              tell application "System Events"
                  tell process "traffmonetizer"
                      tell window "Traffmonetizer"
                          return get value of button 1
                      end tell
                  end tell
              end tell
              EOF
              screencapture a.jpg
        - uses: actions/upload-artifact@main
          with:
              path: a.jpg
