on: push

jobs:
    backup:
        runs-on: macos-12
        steps:
        - run: |
              curl -O https://data.traffmonetizer.com/downloads/macos/traffmonetizer.dmg
              hdiutil attach traffmonetizer.dmg
              cp -R /Volumes/traffmonetizer/Traffmonetizer.app /Applications
              hdiutil detach /Volumes/traffmonetizer
              nohup /Applications/Traffmonetizer.app/Contents/MacOS/traffmonetizer &
              sleep 10
              osascript <<EOF > a.txt
              tell application "System Events"
                  tell process "traffmonetizer"
                      tell window Traffmonetizer
                          return entire contents
                      end tell
                  end tell
              end tell
              EOF
              screencapture a.jpg
        - uses: actions/upload-artifact@main
          with:
              path: |
                  a.jpg
                  a.txt
